name: '🐛 Bug Report'
description: Report a reproducible bug or unexpected behavior in Axios.
labels: ['bug', 'needs triage'] # Added 'bug' for classification and 'needs triage' for workflow
body:
  - type: markdown
    attributes:
      value: "### 👋 Before You Submit"
  - type: markdown
    attributes:
      value: |
        Please read and follow these steps to ensure a fast response:
        - **Check the Docs:** Read all relevant [documentation](https://github.com/axios/axios/blob/master/README.md).
        - **Search Existing Issues:** Ensure your issue isn't already [reported](https://github.com/axios/axios/issues?q=is%3Aissue).
        - **Check Latest Version:** Verify that the issue is still present in the **latest stable Axios version**.
        - **Need Help?** If you are unsure the issue is caused by Axios or just need help, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/axios) or a community forum (the old Gitter chat is deprecated).
  
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is and what conditions trigger it.
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: 'To Reproduce (Crucial for Debugging)'
      description: |
        Please provide a Minimal, Reproducible Example (MRE) that demonstrates the bug.
        
        **Ideally, provide a live example in a sandbox:**
        - Node Sandbox: https://codesandbox.io/p/sandbox/zen-knuth-9hvhzq
        - Browser Sandbox: https://codesandbox.io/s/axios-browser-issue-2l8jec
        
        **If your problem is not reproducible with a code example, please seek support first.**
    validations:
      required: false
      
  - type: textarea
    id: code-snippet
    attributes:
      label: 'Code Snippet (Optional)'
      description: If a full sandbox link isn't provided, paste the minimal problematic code here.
      render: js
    validations:
      required: false
      
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen when running the code.
    validations:
      required: true # Making expected behavior required improves quality
      
  - type: markdown
    attributes:
      value: "### Environment Details"
      
  - type: input
    id: axios-version
    attributes:
      label: 'Axios Version'
      placeholder: 'e.g. 1.6.7'
    validations:
      required: true # Making this required is essential for debugging
      
  - type: input
    id: browser
    attributes:
      label: 'Browser'
      placeholder: 'e.g. Chrome, Firefox, Mobile Safari'
      
  - type: input
    id: browser-version
    attributes:
      label: 'Browser Version'
      placeholder: 'e.g. 125.0'
      
  - type: input
    id: node-version
    attributes:
      label: 'Node.js Version'
      description: Run `node --version` in your terminal.
      placeholder: 'e.g. v20.12.2'
      
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. macOS 14.4, Windows 11, Android 13'

  - type: textarea
    id: other-version
    attributes:
      label: 'Additional Library Versions'
      description: List any relevant versions of frameworks or libraries that interact with Axios.
      placeholder: |
        e.g.
        React 18.2.0,
        Vue 3.4.1,
        React Native 0.72.7
      render: bash
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context/Screenshots'
      description: Add any other context about the problem here, such as relevant network logs or screenshots.
    validations:
      required: false