name: "📝 Documentation"
description: Report an error, typo, or area that needs clarification in the documentation.
labels: ["documentation", "good first issue"] # Added 'good first issue' to encourage quick fixes
body:
  - type: markdown
    attributes:
      value: "### 👋 Thank you for helping us improve our documentation!"
  - type: markdown
    attributes:
      value: |
        If you have already created a fix, feel free to **open a Pull Request directly**! 
        Otherwise, please use the fields below to report the problem.

  - type: textarea
    id: content
    attributes:
      label: "Section/Content To Improve"
      description: Please quote the confusing or incorrect text, or provide a direct link to the section in the documentation (e.g., in README.md).
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Suggested Improvement"
      description: Explain what is confusing or incorrect, and propose the specific changes or wording that would make it better.
    validations:
      required: true

  - type: input
    id: files
    attributes:
      label: "Relevant File(s)"
      description: Which file(s) does this documentation issue affect?
      placeholder: e.g. README.md, CONTRIBUTING.md

  - type: textarea
    id: context
    attributes:
      label: "Additional Context (Optional)"
      description: Add any other context that might be relevant to the documentation.
