name: "✨ Feature Request"
description: Suggest a new idea, enhancement, or feature for Axios.
labels: ["feature", "enhancement"] # Added 'enhancement' label for better classification
body:
  - type: markdown
    attributes:
      value: "### 👋 Before You Submit"
  - type: markdown
    attributes:
      value: |
        Please take a moment to read and follow these steps:
        - **Check the Docs:** Review the [README](https://github.com/axios/axios/blob/master/README.md) to ensure the functionality doesn't already exist.
        - **Search Existing Issues:** Ensure your feature isn't already [requested](https://github.com/axios/axios/issues?q=is%3Aissue).
        - **Need Help?** If you are just looking for usage advice, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/axios) or a community forum for support.

  - type: textarea
    id: description
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: A clear and concise description of the problem you are trying to solve.
      placeholder: I am frustrated when Axios doesn't currently support [X] because [Y reason]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you would like"
      description: A clear and concise description of what you want the feature to do. Include code examples or usage snippets if possible.
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: "Describe alternatives you have considered"
      description: Any alternative solutions, workarounds, or existing features you considered before submitting this request.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context/Screenshots"
      description: Add any other context, designs, or relevant links here.
    validations:
      required: false
