name: "🤔 Support or Usage Question"
description: Please use community channels for questions. Use this only if directed by a maintainer.
labels: ["support", "awaiting-answer"] # Labels to clearly mark this as non-bug/non-feature
body:
  - type: markdown
    attributes:
      value: "## 🛑 STOP! Read Before Submitting 🛑"
  - type: markdown
    attributes:
      value: |
        The Axios issue tracker is primarily for **Bug Reports** and **Feature Requests**.

        For general help, usage questions, and support, please use one of the community resources below for a faster response:

        * **Stack Overflow:** [Search or ask a question using the `axios` tag](https://stackoverflow.com/questions/tagged/axios) (Recommended)
        * **GitHub Discussions:** Check our project's Discussions tab (if available).

        Issues filed here will likely be closed and redirected. **Only proceed if you believe your question is complex or you were explicitly asked to file an issue.**

  - type: textarea
    id: description
    attributes:
      label: "Your Question or Usage Scenario"
      description: Describe your question, problem, or usage scenario clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: "Relevant Code Snippet"
      description: Provide the specific code you are using that illustrates your question.
      render: js
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: "What did you expect to happen?"
      description: Explain the behavior you were trying to achieve.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Environment (Technical Context)"

  - type: input
    id: axios-version
    attributes:
      label: "Axios Version"
      placeholder: "e.g. 1.6.7"

  - type: input
    id: node-version
    attributes:
      label: "Node.js Version (if applicable)"
      description: "node --version"
      placeholder: "e.g. v20.12.2"

  - type: input
    id: os
    attributes:
      label: "OS"
      placeholder: "e.g. macOS 14.4, Windows 11"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context/Screenshots"
      description: Add any other context or screenshots that help explain your question.
    validations:
      required: false
